name: my_first_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+10

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.1.0
  
  tutorial_coach_mark: ^1.2.9
  # アイコン
  cupertino_icons: ^1.0.8
  
  # 画像選択・スキャン
  image_picker: ^1.1.2
  cunning_document_scanner: ^1.4.0
  
  # 文字認識 (OCR)
  google_mlkit_text_recognition: ^0.15.0
  
  # データベース
  sqflite: ^2.3.3+1
  path: ^1.9.0
  
  # 画像処理・AI
  image: ^4.2.0
  
  # 日付フォーマット
  intl: ^0.20.2
  google_generative_ai: ^0.4.7
  google_mobile_ads: ^7.0.0
  crypto: ^3.0.7
  http: ^1.6.0
  shared_preferences: ^2.5.4
  flutter_dotenv: ^5.1.0
  device_info_plus: ^11.0.0

  # これを追加dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: "0.13.1"
  change_app_package_name: ^1.1.0

# ▼▼ ここから下を全部書き換える ▼▼

flutter:
  uses-material-design: true

  # ★ここに「アニメ画像」と「アイコン」を登録します
  # ※インデント（左のスペース）をこの通りに合わせてください
  assets:
    - assets/icon.png            # ← pngに変更しました！
    - assets/PC1.png     # ← アニメ画像1
    - assets/PC2.png     # ← アニメ画像2
    - assets/print1.png
    - assets/print2.png 
    - assets/print3.png
    - assets/print4.png  
    - assets/fry1.png
    - assets/fry2.png
    - assets/fry3.png
    - assets/fry4.png
    - assets/fry5.png
    - assets/fry6.png
    - assets/bike.png
    - assets/start.png
    - assets/wall.png
    - assets/clipboard.png
    - assets/tv.png
    
    - assets/camera.png
    - assets/lamp.png
    - assets/start.png


     # ← アニメ画像3
    # ... 他に使いたい画像があればここに追加してください

# ★アイコンを作るための設定（一番左端に寄せて書く！）
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"  # ← ここもpngに変更済み！
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon.png"

